---
- import_tasks: omnibus.yml
  when: gitlab_running_platform == 'omnibus'

- import_tasks: docker.yml
  when: gitlab_running_platform == 'docker'

- name: Add backup cron jobs
  cron:
    name: '{{item.name}}'
    job: "{{'docker exec -t gitlab /bin/sh -c' if gitlab_running_platform == 'docker'}} '{{item.job}}'"
    user: root
    state: present
    disabled: '{{not gitlab_backup_enabled}}'
    minute:   '{{gitlab_backup_frequency.minute | default(omit)}}'
    hour:     '{{gitlab_backup_frequency.hour | default(omit)}}'
    day:      '{{gitlab_backup_frequency.day | default(omit)}}'
    month:    '{{gitlab_backup_frequency.month | default(omit)}}'
    weekday:  '{{gitlab_backup_frequency.weekday | default(omit)}}'
    special_time: '{{gitlab_backup_frequency.special_time | default(omit)}}'
  with_items:
    - name: Gitlab data backup
      job: 'gitlab-rake gitlab:backup:create {{gitlab_backup_options}}'
    - name: Gitlab config backup
      job: 'umask 0077; tar cf /var/opt/gitlab/backups/$(date +"%s_%Y_%m_%d_gitlab_config.tar") -C / etc/gitlab etc/ssh && find /var/opt/gitlab/backups/ -name "*_gitlab_config.tar" -not -newermt "-{{gitlab_backup_keep_time}} seconds" -delete'
